#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9  

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color	 '#242730'
bspc config focused_border_color '#579df0'
bspc config focus_follows_pointer true

#bspc rule -a gimp desktop=^8 state=floating follow=on
bspc rule -a Zathura state=tiled

##########################
##########################
##			##
##	AUTOSTART	##
##			##
##########################
##########################

#feh --bg-fill --randomize /home/dilip/Wallpapers/ &
nitrogen --restore &
urxvtd -q -o -f &
polybar -c ~/.config/polybar/config main &
nm-applet &
picom --experimental-backend &
telegram-desktop -startintray &
#compton --config ~/.config/compton/compton.conf &
#conky -c .conky/sidebar-desktop &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
