#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9  

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color	 '#202229'
bspc config focused_border_color '#5481b6'
bspc config focus_follows_pointer true

#bspc rule -a gimp desktop=^8 state=floating follow=on


##########################
##########################
##			##
##	AUTOSTART	##
##			##
##########################
##########################

#feh --bg-fill --randomize /home/dilip/Wallpapers/ &
nitrogen --restore &
polybar -c ~/.config/polybar/config main &
nm-applet &
picom --experimental-backend &
#compton --config ~/.config/compton/compton.conf &
conky -c .conky/sidebar-desktop
